version: "3.8"
services:
  dc:
    build: .
#    build: 
#      context: .
#      args:
#        - PARAM=--host-config host-master.xml -b 0.0.0.0 -bmanagement 0.0.0.0
    ports:
      - "9990:9990"
      - "9999:9999"
    networks:
      - aa
#      aa:
#        ipv4_address: 172.19.0.2
    environment:
      - LGR_JAVA_OPTS
      - DB_HOST_IP
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dc:9990"]
#      interval: 1m30s
      interval: 30s
      timeout: 10s
      retries: 3
#      start_period: 2m
  hc-1:
    restart: on-failure
#    build: .
    build:
      context: .
      dockerfile: Dockerfile.host
      args:
        WILDFLY_NAME: wildfly_1_test
        CLUSTER_PW: secret_password
#    ports:
#      - 8081:8080
#      - 8444:8443
    networks:
      - aa
#      aa:
#        ipv4_address: 172.19.0.3
    depends_on:
      dc:
        condition: service_healthy
    environment:
      - LGR_JAVA_OPTS
      - DB_HOST_IP
  hc-2:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.host
      args:
        WILDFLY_NAME: wildfly_2_test
        CLUSTER_PW: secret_password
#    ports:
#      - 8082:8080
#      - 8445:8443
    networks:
      - aa
    depends_on:
      dc:
        condition: service_healthy
    environment:
      - LGR_JAVA_OPTS
      - DB_HOST_IP
  balancing:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.balancing
      args:
        WILDFLY_NAME: balancing
        CLUSTER_PW: secret_password
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - aa
    depends_on:
      - dc
      - hc-1
    environment:
      - LGR_JAVA_OPTS
      - DB_HOST_IP

networks:
  aa:
#    ipam:
#      driver: default
